Repository wecode-bootcamp-korea/33-2nd-CREAM-frontend, pull requests merged in 2022-06, with the labels that each got.

#1 [33기 이윤섭] MODIFIED: theme 설정
  package-lock.json
  package.json
  src/styles/theme.js
Labels: 멘토 리뷰 요청

#2 [33기 김슬비] Footer 레이아웃 작업
  src/Router.js
  src/components/footer/Footer.js
Labels: 수정 요청

#4 [33기 장수연] 메인 리스트 페이지 레이아웃
  public/data/productsData.json
  public/images/ItemList/bookmark.png
  public/images/ItemList/like.png
  public/images/ItemList/up-down.png
  src/Router.js
  src/pages/main/components/itemList/Banner.js
  src/pages/main/components/itemList/BannerListData.js
  src/pages/main/components/itemList/Category.js
  src/pages/main/components/itemList/Item.js
  src/pages/main/components/itemList/ItemList.js
  src/pages/main/components/itemList/categoriesListData.js
  src/styles/GlobalStyle.js
Labels: 완료

#3 [33기 유지후] 메인 리스트 페이지 Carousel 기능 구현
  package-lock.json
  package.json
  public/images/codeKata 6.PNG
  public/images/img1.jpg
  public/images/img2.png
  public/images/img3.jpg
  public/images/img4.jpg
  public/images/img5.jpg
  public/images/img6.jpg
  src/pages/main/Main.js
  src/pages/main/components/carousel/Carousel.js
  src/pages/main/components/slider/Slider.js
  src/styles/GlobalStyle.js
Labels: 멘토 리뷰 요청

#5 [33기 이윤섭] ADD: 상세페이지 구현
  package-lock.json
  package.json
  public/data/goodsData.json
  public/data/graphData.json
  public/data/sizeData.json
  src/Router.js
  src/pages/deals/Buy.js
  src/pages/deals/components/SelectDealType.js
  src/pages/deals/components/SizeButtons.js
  src/pages/goodsDetail/GoodsDetail.js
  src/pages/goodsDetail/components/LeftContents.js
  src/pages/goodsDetail/components/RightContents.js
  src/pages/goodsDetail/components/rightSide/ConditionChart.js
  src/pages/goodsDetail/components/rightSide/DealChecklist.js
  src/pages/goodsDetail/components/rightSide/DealsModal.js
  src/pages/goodsDetail/components/rightSide/GoodsInfo.js
  src/pages/goodsDetail/components/rightSide/GoodsSummary.js
  src/pages/goodsDetail/components/rightSide/PriceCondition.js
  src/pages/goodsDetail/components/rightSide/StickySummary.js
  src/pages/itemDetail/itemDetail.js
  src/styles/theme.js
Labels: 수정 요청

#7 [33기 김슬비] Add : Nav 레이아웃 / 폰트설정
  public/index.html
  src/Router.js
  src/components/nav/Nav.js
  src/config.js
  src/styles/GlobalStyle.js
Labels: 멘토 리뷰 요청

#9 [33기 김슬비] ADD : 소셜 로그인 기능구현
  .gitignore
  src/Router.js
  src/components/nav/Nav.js
  src/config.js
  src/pages/users/Redirect.js
  src/pages/users/login/Login.js
  src/pages/users/login/LoginData.js
  src/styles/GlobalStyle.js
Labels: 멘토 리뷰 요청

#11 Add: 메인 페이지 병합
  public/images/bannerImage/bag.png
  public/images/bannerImage/game.png
  public/images/bannerImage/jean.png
  public/images/bannerImage/shoes1.png
  public/images/bannerImage/shoes2.png
  public/images/bannerImage/shoes3.png
  public/images/bannerImage/shoes4.png
  public/images/bannerImage/tshirt.png
  src/pages/main/Main.js
  src/pages/main/components/itemList/BannerListData.js
  src/pages/main/components/itemList/Category.js
  src/pages/main/components/itemList/Components/Banner.js
  src/pages/main/components/itemList/Components/Category.js
  src/pages/main/components/itemList/Components/Clothing.js
  src/pages/main/components/itemList/Components/Item.js
  src/pages/main/components/itemList/Components/ItemNotFound.js
  src/pages/main/components/itemList/Components/Price.js
  src/pages/main/components/itemList/Components/SearchBar.js
  src/pages/main/components/itemList/Components/Shoes.js
  src/pages/main/components/itemList/Components/SortListData.js
  src/pages/main/components/itemList/Data/bannerListData.js
  src/pages/main/components/itemList/Data/categoryData.js
  src/pages/main/components/itemList/ItemList.js
  src/pages/main/components/itemList/categoriesListData.js
  src/styles/GlobalStyle.js
Labels: 완료

#12 [33기 김슬비] ADD : 소셜 로그인 추가 기능구현 및 리팩토링
  package-lock.json
  package.json
  src/components/footer/Footer.js
  src/components/nav/Nav.js
  src/pages/users/Redirect.js
Labels: Conflict 해결 요청
